spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/rabispedro/ms-income-config

server:
  port: 8888
