CREATE TABLE IF NOT EXISTS "customer" (
	"id" UUID DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
	"name" VARCHAR(255) NOT NULL,
	"email" VARCHAR(255) NOT NULL UNIQUE,
	"password" VARCHAR(255) NOT NULL
);
