INSERT INTO "Role"("name")
VALUES
	('ROLE_ADMINISTRATOR'),
	('ROLE_SOFTWARE_ENGINEER'),
	('ROLE_DESIGNER'),
	('ROLE_PRODUCT_OWNER'),
	('ROLE_QUALITY_ASSURANCER'),
	('ROLE_DATA_ENGINEER'),
	('ROLE_AGILIST');
